import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../public/assets/styles/globals.css";

import { AuthProvider } from "@/contexts/authContext"; // Import UserProvider
import Content from "@/app/layoutContent"; // Import Content
import { auth0 } from "@/lib/auth0"; // Import Auth0 for session fetching

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth0.getSession(); // 🔹 Fetch latest session on request

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialSession={session}>
          <Content>{children}</Content>
        </AuthProvider>
      </body>
    </html>
  );
}
